# Generated by Django 2.2.6 on 2019-10-31 11:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('socialaccount', '0003_extra_data_default_dict'),
    ]

    operations = [
        migrations.CreateModel(
            name='AppleSocialApp',
            fields=[
                ('socialapp_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='socialaccount.SocialApp')),
                ('team_id', models.CharField(help_text='Apple TeamID', max_length=191, verbose_name='team id')),
                ('key_id', models.CharField(help_text='Apple KeyID', max_length=256, verbose_name='key id')),
                ('auth_key', models.FileField(help_text='Apple AuthKey', upload_to='', verbose_name='authentication key')),
            ],
            options={
                'verbose_name': 'social application',
                'verbose_name_plural': 'social applications',
            },
            bases=('socialaccount.socialapp',),
        ),
    ]
